require('settings')
require('mappings')
require('colorschemes-config.nightfox')
require('packer-config')
require('nvim-tree-config')
require('treesitter-config')
require('lsp')
require('nvim-cmp-config')
